variable "region" {}
variable "vpc_cidr" {}
variable "project_name" {}
variable "public_subnet_az1_cidr" {}
variable "public_subnet_az2_cidr" {}
variable "private_subnet_az1_cidr" {}
variable "private_subnet_az2_cidr" {}
variable "secure_subnet_az1_cidr" {}
variable "secure_subnet_az2_cidr" {}